services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bin/setup --skip-server --skip-dependencies && bundle exec rails server -b 0.0.0.0"
#    command: bash -c "bin/setup --skip-server --skip-dependencies && bundle exec rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/rails
    working_dir: /rails

volumes:
  postgres_data:
